# ©AngelaMos | 2026
# Dev

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: development
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5455:5432"
    networks:
      - dark_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d devdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6377:6379"
    networks:
      - dark_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://dev:development@postgres:5432/devdb
      REDIS_URL: redis://redis:6379
      RUST_LOG: debug
      PORT: 8000
      ENVIRONMENT: development
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      SQLX_OFFLINE: "true"
    ports:
      - "8111:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dark_network
    volumes:
      - ./backend:/app:delegated
      - backend_target:/app/target
      - backend_cargo_registry:/usr/local/cargo/registry
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4002:3000"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8090
      VITE_DEV_MODE: true
    depends_on:
      - backend
    networks:
      - dark_network
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dark_network
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  frontend_node_modules:
    driver: local
  backend_target:
    driver: local
  backend_cargo_registry:
    driver: local

networks:
  dark_network:
    driver: bridge
