# ©AngelaMos | 2025
# Dev

FROM rust:1.86-slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    libpq-dev \
    build-essential \
    git \
    curl \
    postgresql-client \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch --locked

WORKDIR /app

COPY Cargo.toml ./Cargo.toml
COPY Cargo.lock ./Cargo.lock
COPY src/database ./database

COPY .sqlx ./.sqlx

RUN mkdir -p src && echo "fn main() {}" > src/main.rs
COPY build.rs ./

RUN cargo build
RUN rm -rf src

ENV RUST_LOG=debug
ENV RUST_BACKTRACE=1
ENV ENVIRONMENT=development
ENV PORT=3001

EXPOSE 3001

CMD ["cargo", "watch", "-x", "run"]
