# Production Prometheus configuration for comprehensive performance monitoring
# Optimized for production with longer retention and more focused monitoring

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'dark-performance-prod'
    environment: 'production'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Backend metrics - primary monitoring target
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s

  # Docker container monitoring (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'

# Remote storage configuration (optional - for production scaling)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.example.com/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# Alerting configuration (disabled for basic production)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093